name: Tmate Debug Session
on:
  workflow_dispatch: # 手动触发工作流，运行方式：通过 GitHub 仓库的“Actions”标签页手动启动
                    # 参考：https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # 设置任务超时为 3 小时

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # 动作来源：https://github.com/actions/checkout
      # 用途：检出代码库到运行环境

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true # 限制仅触发者可通过 SSH 访问
        timeout-minutes: 180 # tmate 会话超时为 3 小时
      # 动作来源：https://github.com/mxschmitt/action-tmate
      # 用途：启动 tmate 会话以进行远程调试
