name: tmate SSH Session

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tmate:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # 设置运行时间为 3 小时

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install tmate
      run: |
        sudo apt-get update
        sudo apt-get install -y tmate

    - name: Start tmate session
      run: |
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
        tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
        sleep 10800 # 保持会话 3 小时 (10800 秒)

    - name: Keep workflow alive
      run: |
        echo "tmate session is running. Connect using the SSH or Web URL displayed above."
