name: Tmate Debug Session
on:
  workflow_dispatch: # 允许手动触发 workflow

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # 设置 3 小时超时

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true # 限制仅触发者可访问
        timeout-minutes: 180 # 再次确认 3 小时超时